/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.Uber;
import model.UberList;

/**
 *
 * @author krupa
 */
public class viewPanel extends javax.swing.JPanel {

    /**
     * Creates new form viewPanel
     * @param uberObj
     */
    UberList ubercars;
    
    public viewPanel(UberList ubercars) {
        initComponents();
        
        this.ubercars = ubercars;
        
        insertToTable();
        Date currDate = new Date();

        txtUpdatedTime.setText(currDate.toString());
        txtUpdatedTime.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lblHeading = new javax.swing.JLabel();
        lblCertiExp = new javax.swing.JLabel();
        lblIsAvail = new javax.swing.JLabel();
        lblManufctNme = new javax.swing.JLabel();
        lblCarName = new javax.swing.JLabel();
        lblNumOfSeat = new javax.swing.JLabel();
        lblMnfYr = new javax.swing.JLabel();
        lblSerialNo = new javax.swing.JLabel();
        lblModelNo = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblUpdateHeader = new javax.swing.JLabel();
        txtCarNmeView = new javax.swing.JTextField();
        txtCarMnfNameView = new javax.swing.JTextField();
        jYearMnfYrView = new com.toedter.calendar.JYearChooser();
        txtSerialNumView = new javax.swing.JTextField();
        txtModelNumView = new javax.swing.JTextField();
        txtCityView = new javax.swing.JTextField();
        jDateCertiExpView = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarReg = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        comboIsAvailView = new javax.swing.JComboBox<>();
        comboSeatNumView = new javax.swing.JComboBox<>();
        txtUpdatedTime = new javax.swing.JTextField();
        lblUpdatedTime = new javax.swing.JLabel();

        setBackground(new java.awt.Color(193, 233, 242));

        lblHeading.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("View Registration Details");
        lblHeading.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblHeading.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(lblHeading);

        lblCertiExp.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCertiExp.setText("Car Maintenance Expiry Certificate");
        lblCertiExp.setToolTipText("");
        lblCertiExp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCertiExp.setName(""); // NOI18N

        lblIsAvail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblIsAvail.setText("Is Available");
        lblIsAvail.setToolTipText("");
        lblIsAvail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIsAvail.setName(""); // NOI18N

        lblManufctNme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblManufctNme.setText("Car Manufacturer Name");
        lblManufctNme.setToolTipText("");
        lblManufctNme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblManufctNme.setName(""); // NOI18N

        lblCarName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCarName.setText("Car Name");
        lblCarName.setToolTipText("");
        lblCarName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCarName.setName(""); // NOI18N

        lblNumOfSeat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNumOfSeat.setText("Number of seats in a car");
        lblNumOfSeat.setToolTipText("");
        lblNumOfSeat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNumOfSeat.setName(""); // NOI18N

        lblMnfYr.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblMnfYr.setText("Car Manufacturer Year");
        lblMnfYr.setToolTipText("");
        lblMnfYr.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMnfYr.setName(""); // NOI18N

        lblSerialNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblSerialNo.setText("Car Serial Number");
        lblSerialNo.setToolTipText("");
        lblSerialNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSerialNo.setName(""); // NOI18N

        lblModelNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblModelNo.setText("Car model Number");
        lblModelNo.setToolTipText("");
        lblModelNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblModelNo.setName(""); // NOI18N

        lblCity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblCity.setText("City");
        lblCity.setToolTipText("");
        lblCity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCity.setName(""); // NOI18N

        lblUpdateHeader.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUpdateHeader.setForeground(new java.awt.Color(255, 0, 51));
        lblUpdateHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateHeader.setText("Select a record for updating registration details:");

        txtCarNmeView.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCarNmeView.setToolTipText("");
        txtCarNmeView.setName(""); // NOI18N
        txtCarNmeView.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCarNmeViewKeyPressed(evt);
            }
        });

        txtCarMnfNameView.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCarMnfNameView.setToolTipText("");
        txtCarMnfNameView.setName(""); // NOI18N
        txtCarMnfNameView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarMnfNameViewActionPerformed(evt);
            }
        });

        jYearMnfYrView.setToolTipText("");
        jYearMnfYrView.setName(""); // NOI18N

        txtSerialNumView.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtSerialNumView.setToolTipText("");
        txtSerialNumView.setName(""); // NOI18N
        txtSerialNumView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumViewActionPerformed(evt);
            }
        });

        txtModelNumView.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtModelNumView.setToolTipText("");
        txtModelNumView.setName(""); // NOI18N
        txtModelNumView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumViewActionPerformed(evt);
            }
        });

        txtCityView.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCityView.setToolTipText("");
        txtCityView.setName(""); // NOI18N

        tblCarReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Name", "Is Car Available", "Car Manufacturer Name", "Car Manufacturer Year", "Number of a Seats in a car", "Car Serial Number", "Car Model Number", "City", "Car Maintenance Expiry Date", "Is Expired"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    tblCarReg.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tblCarRegMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(tblCarReg);

    btnSave.setBackground(new java.awt.Color(204, 204, 204));
    btnSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    btnSave.setText("Save");
    btnSave.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    btnSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveActionPerformed(evt);
        }
    });

    comboIsAvailView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

    comboSeatNumView.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

    lblUpdatedTime.setText("Last Updated Time: ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblUpdateHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(155, 155, 155)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNumOfSeat, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addComponent(lblModelNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSerialNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIsAvail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblManufctNme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMnfYr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCertiExp, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(340, 340, 340)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCarNmeView, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCarMnfNameView)
                            .addComponent(txtSerialNumView)
                            .addComponent(txtModelNumView)
                            .addComponent(txtCityView)
                            .addComponent(jYearMnfYrView, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateCertiExpView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(comboIsAvailView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboSeatNumView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 147, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)))
            .addContainerGap())
        .addGroup(layout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addComponent(lblUpdatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(73, 73, 73)
            .addComponent(txtUpdatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(464, 464, 464))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCarName, lblCertiExp, lblCity, lblIsAvail, lblManufctNme, lblMnfYr, lblModelNo, lblNumOfSeat, lblSerialNo});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(lblUpdatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtUpdatedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblUpdateHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lblCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCarNmeView))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblIsAvail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(comboIsAvailView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lblManufctNme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCarMnfNameView))
            .addGap(18, 18, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lblMnfYr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumOfSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboSeatNumView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jYearMnfYrView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblSerialNo)
                .addComponent(txtSerialNumView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblModelNo)
                .addComponent(txtModelNumView))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtCityView)
                .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lblCertiExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDateCertiExpView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(25, 25, 25)
            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(208, 208, 208))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCarName, lblCertiExp, lblCity, lblIsAvail, lblManufctNme, lblMnfYr, lblModelNo, lblNumOfSeat, lblSerialNo});

    }// </editor-fold>//GEN-END:initComponents

    private void txtCarNmeViewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarNmeViewKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) ){
            txtCarNmeView.setEditable(true);
        }
        else{
            txtCarNmeView.setEditable(false);
            JOptionPane.showMessageDialog(txtCarNmeView, "Error: Car name cannot be Null, digits or consists of whitespaces.");
        }
    }//GEN-LAST:event_txtCarNmeViewKeyPressed

    private void txtCarMnfNameViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarMnfNameViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarMnfNameViewActionPerformed

    private void txtSerialNumViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumViewActionPerformed

    private void txtModelNumViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumViewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Uber uberObjNew = new Uber();
        
        int i = tblCarReg.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
        
        uberObjNew.setCarName(txtCarNmeView.getText());
        if(comboIsAvailView.getSelectedItem().toString().toLowerCase().equals("yes"))
        {
            uberObjNew.setIsAvailable(true);
        }
        else{
            uberObjNew.setIsAvailable(false);
        }
        uberObjNew.setCarManufacturer(txtCarMnfNameView.getText());
        uberObjNew.setCarManufacturingYear(jYearMnfYrView.getYear());
        uberObjNew.setNumOfSeats(Integer.parseInt(comboSeatNumView.getSelectedItem().toString()));
        
//        for(Uber uber: ubercars.getUberCars()){
//            if(txtSerialNumView.getText().equals(uber.getSerialNum())){
//                JOptionPane.showMessageDialog(txtSerialNumView, "Error: Car serial number is not unique. Duplicate record found.");
//               return;
//            }
//            else{
                uberObjNew.setSerialNum(txtSerialNumView.getText());
//            }
//        }
        
        uberObjNew.setModelNum(txtModelNumView.getText());
        uberObjNew.setMaintenanceExpiryCerti(jDateCertiExpView.getDate());
        uberObjNew.setCity(txtCityView.getText());
        Date currDate = new Date();
        for( Uber carObj : ubercars.getUberCars() ){
            if((uberObjNew.getMaintenanceExpiryCerti().before(currDate))){  
                    uberObjNew.setIsExpired("Expired");
                }
            else if((currDate.before(uberObjNew.getMaintenanceExpiryCerti()))){
                    uberObjNew.setIsExpired("Not Expired");
            }
        }                  
        ubercars.getUberCars().set(tblCarReg.getSelectedRow(), uberObjNew);
        
        insertToTable();
        ubercars.setUpdatedTime(currDate);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblCarRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCarRegMouseClicked
        // TODO add your handling code here:
        
            int i = tblCarReg.getSelectedRow();
            if(i<0){
                JOptionPane.showMessageDialog(this, "Please select a row to update.");
            }

            DefaultTableModel model = (DefaultTableModel)tblCarReg.getModel();
            
            txtCarNmeView.setText(model.getValueAt(i, 0).toString());
//            txtIsAvail.setText((model.getValueAt(i, 1).toString()));
            comboIsAvailView.setSelectedItem(model.getValueAt(i, 1).toString());
            txtCarMnfNameView.setText(model.getValueAt(i, 2).toString());
            jYearMnfYrView.setValue((int) model.getValueAt(i, 3));
//            txtSeat.setText((model.getValueAt(i, 4).toString()));
            comboSeatNumView.setSelectedItem(model.getValueAt(i, 4).toString());
            txtSerialNumView.setText(model.getValueAt(i, 5).toString());
            txtSerialNumView.setEditable(false);
            txtModelNumView.setText(model.getValueAt(i, 6).toString());
            txtCityView.setText(model.getValueAt(i, 7).toString());
            jDateCertiExpView.setDate((Date) model.getValueAt(i, 8));
            
    }//GEN-LAST:event_tblCarRegMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboIsAvailView;
    private javax.swing.JComboBox<String> comboSeatNumView;
    private com.toedter.calendar.JDateChooser jDateCertiExpView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JYearChooser jYearMnfYrView;
    private javax.swing.JLabel lblCarName;
    private javax.swing.JLabel lblCertiExp;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblIsAvail;
    private javax.swing.JLabel lblManufctNme;
    private javax.swing.JLabel lblMnfYr;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblNumOfSeat;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblUpdateHeader;
    private javax.swing.JLabel lblUpdatedTime;
    private javax.swing.JTable tblCarReg;
    private javax.swing.JTextField txtCarMnfNameView;
    private javax.swing.JTextField txtCarNmeView;
    private javax.swing.JTextField txtCityView;
    private javax.swing.JTextField txtModelNumView;
    private javax.swing.JTextField txtSerialNumView;
    private javax.swing.JTextField txtUpdatedTime;
    // End of variables declaration//GEN-END:variables

    private void insertToTable() {
        DefaultTableModel model = (DefaultTableModel)tblCarReg.getModel();
        tblCarReg.setRowHeight(40);
        
        tblCarReg.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
//        JTable table = new JTable();
//        table.setRowSelectionAllowed(true);
//        tblCarReg.setRowSelectionAllowed(true);
//tblCarReg.changeSelection(0, 0, false, false);

        tblCarReg.getTableHeader().setPreferredSize(new Dimension(250, 40));
        tblCarReg.getTableHeader().setBackground(Color.RED);
        tblCarReg.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 20));
//        tblCarReg.getTableHeader().setForeground(Color.WHITE);
//        ((DefaultTableCellRenderer)tblCarReg.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        tblCarReg.setFont(new Font("Times New Roman", Font.PLAIN,18 ));
        model.setRowCount(0);
        
        
        for(Uber uberObj: ubercars.getUberCars()){
           if(        (uberObj.getCarName()== null || uberObj.getCarName().isEmpty()) 
                   || (uberObj.getCarManufacturer()== null || uberObj.getCarManufacturer().isEmpty()) 
                   || (uberObj.getSerialNum()== null || uberObj.getSerialNum().isEmpty()) 
                   || (uberObj.getModelNum()== null || uberObj.getModelNum().isEmpty()) 
                   || (uberObj.getCity()== null || uberObj.getCity().isEmpty()) 
                   || (uberObj.getMaintenanceExpiryCerti()== null || uberObj.getCarName().isEmpty()) 
            ){
               return;
           }
           else{
            Object[] row = new Object[10];
            row[0] = uberObj.getCarName();
            row[1] = ((uberObj.isIsAvailable() == true) ? "Yes" : "No");
            row[2] = uberObj.getCarManufacturer();
            row[3] = uberObj.getCarManufacturingYear();
            row[4] = uberObj.getNumOfSeats();
            row[5] = uberObj.getSerialNum();
            row[6] = uberObj.getModelNum();
            row[7] = uberObj.getCity();
            row[8] = uberObj.getMaintenanceExpiryCerti();
            row[9] = uberObj.getIsExpired();
            model.addRow(row);
           }
            
        }
        
          
    } 

}
