/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import model.Person;

/**
 *
 * @author krupa
 */

public class displayPanel extends javax.swing.JPanel {

    /**
     * Creates new form displayPanel
     * @param ImagePath
     * @param lblName
     * @return 
     */

    //230*170

public ImageIcon imgResize(String ImagePath, JLabel lblName)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblName.getWidth(), lblName.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    public displayPanel(Person personObj) {
        initComponents();

        txtViewName.setText(personObj.getName());
        txtViewName.setEditable(false);
        txtViewAddress.setText(personObj.getGeographicData()); 
        txtViewDob.setText(personObj.getDateOfBirth().toString());
        txtViewTeleNum.setText(personObj.getPhone());
        txtViewFAXNum.setText(personObj.getFaxNumber());
        txtViewEmailId.setText(personObj.getEmail());
        txtViewSSN.setText(personObj.getSsn());
        txtViewMedicalRecordNum.setText(personObj.getMedicalRecordNumber());
        txtViewHealthPlanBnfId.setText(personObj.getHealthPlanBeneficiaryNumber());
        txtViewBankAccNum.setText(personObj.getBankAccountNumbers());
        txtViewLicenseNum.setText(personObj.getLicenseNumber());
        txtViewVehicleId.setText(String.valueOf(personObj.getVehicleIdentifiers()));
        txtViewDeviceId.setText(String.valueOf(personObj.getDeviceIdentifiers()));
        txtViewLinkedin.setText(personObj.getLinkedInId());
        txtViewIp.setText(personObj.getIpAddresses());
        lblBiometric.setBounds(10,10,670,250);
        lblFullFaceImg.setBounds(10,10,670,250);
        lblBiometric.setIcon(imgResize(personObj.getBioMetricUrl(), lblBiometric));  
        lblFullFaceImg.setIcon(imgResize(personObj.getBioMetricUrl(), lblFullFaceImg));        

        

//        txtViewBioId.setText(personObj.g());
//Full face images -> add in getter setter in person class too.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblCreatePersonProfile = new javax.swing.JLabel();
        lblViewName = new javax.swing.JLabel();
        lblViewAddress = new javax.swing.JLabel();
        lblViewDob = new javax.swing.JLabel();
        lblViewTelephoneNum = new javax.swing.JLabel();
        lblViewFax = new javax.swing.JLabel();
        lblViewEmail = new javax.swing.JLabel();
        lblViewSSN = new javax.swing.JLabel();
        lblViewMedicalRecordNum = new javax.swing.JLabel();
        lblViewDeviceId = new javax.swing.JLabel();
        lblViewLinkedIn = new javax.swing.JLabel();
        lblViewIP = new javax.swing.JLabel();
        lblViewHealthPlanBnfNum = new javax.swing.JLabel();
        lblViewBiometricId = new javax.swing.JLabel();
        lblViewBankAccNum = new javax.swing.JLabel();
        lblViewLicenseNum = new javax.swing.JLabel();
        lblViewVehicleId = new javax.swing.JLabel();
        lblViewFullFaceImage = new javax.swing.JLabel();
        txtViewName = new javax.swing.JTextField();
        txtViewTeleNum = new javax.swing.JTextField();
        txtViewFAXNum = new javax.swing.JTextField();
        txtViewEmailId = new javax.swing.JTextField();
        txtViewSSN = new javax.swing.JTextField();
        txtViewMedicalRecordNum = new javax.swing.JTextField();
        txtViewDeviceId = new javax.swing.JTextField();
        txtViewLinkedin = new javax.swing.JTextField();
        txtViewIp = new javax.swing.JTextField();
        txtViewHealthPlanBnfId = new javax.swing.JTextField();
        txtViewBankAccNum = new javax.swing.JTextField();
        txtViewLicenseNum = new javax.swing.JTextField();
        txtViewVehicleId = new javax.swing.JTextField();
        txtViewDob = new javax.swing.JTextField();
        txtViewAddress = new javax.swing.JTextField();
        lblBiometric = new javax.swing.JLabel();
        lblFullFaceImg = new javax.swing.JLabel();

        lblCreatePersonProfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCreatePersonProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreatePersonProfile.setText("Display Person Profile");
        lblCreatePersonProfile.setAutoscrolls(true);

        lblViewName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewName.setText("Name");
        lblViewName.setAutoscrolls(true);

        lblViewAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewAddress.setText("Address");
        lblViewAddress.setAutoscrolls(true);

        lblViewDob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewDob.setText("DOB");
        lblViewDob.setAutoscrolls(true);

        lblViewTelephoneNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewTelephoneNum.setText("Telephone numbers");
        lblViewTelephoneNum.setAutoscrolls(true);

        lblViewFax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFax.setText("FAX number");
        lblViewFax.setAutoscrolls(true);

        lblViewEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewEmail.setText("Email addresses");
        lblViewEmail.setAutoscrolls(true);

        lblViewSSN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewSSN.setText("Social Security Number");
        lblViewSSN.setAutoscrolls(true);

        lblViewMedicalRecordNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewMedicalRecordNum.setText("Medical Record Number");
        lblViewMedicalRecordNum.setAutoscrolls(true);

        lblViewDeviceId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewDeviceId.setText("Device identifiers and serial numbers");
        lblViewDeviceId.setAutoscrolls(true);

        lblViewLinkedIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLinkedIn.setText("LinkedIn");
        lblViewLinkedIn.setAutoscrolls(true);

        lblViewIP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewIP.setText("Internet protocol addresses");
        lblViewIP.setAutoscrolls(true);

        lblViewHealthPlanBnfNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewHealthPlanBnfNum.setText("Health plan beneficiary number");
        lblViewHealthPlanBnfNum.setAutoscrolls(true);

        lblViewBiometricId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewBiometricId.setText("Biometric identifiers");
        lblViewBiometricId.setAutoscrolls(true);

        lblViewBankAccNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewBankAccNum.setText("Bank account numbers");
        lblViewBankAccNum.setAutoscrolls(true);

        lblViewLicenseNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLicenseNum.setText("Certificate/license number ");
        lblViewLicenseNum.setAutoscrolls(true);

        lblViewVehicleId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewVehicleId.setText("Vehicle identifiers and serial numbers including license plates ");
        lblViewVehicleId.setAutoscrolls(true);

        lblViewFullFaceImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFullFaceImage.setText("Full face photos and comparable images");
        lblViewFullFaceImage.setAutoscrolls(true);

        txtViewName.setEditable(false);

        txtViewTeleNum.setEditable(false);

        txtViewFAXNum.setEditable(false);

        txtViewEmailId.setEditable(false);

        txtViewSSN.setEditable(false);

        txtViewMedicalRecordNum.setEditable(false);

        txtViewDeviceId.setEditable(false);

        txtViewLinkedin.setEditable(false);

        txtViewIp.setEditable(false);
        txtViewIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewIpActionPerformed(evt);
            }
        });

        txtViewHealthPlanBnfId.setEditable(false);

        txtViewBankAccNum.setEditable(false);
        txtViewBankAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewBankAccNumActionPerformed(evt);
            }
        });

        txtViewLicenseNum.setEditable(false);

        txtViewVehicleId.setEditable(false);

        txtViewDob.setEditable(false);
        txtViewDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewDobActionPerformed(evt);
            }
        });

        txtViewAddress.setEditable(false);
        txtViewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewAddressActionPerformed(evt);
            }
        });

        lblBiometric.setToolTipText("");
        lblBiometric.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFullFaceImg.setBackground(new java.awt.Color(204, 204, 204));
        lblFullFaceImg.setToolTipText("");
        lblFullFaceImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblViewName)
                            .addComponent(lblViewAddress)
                            .addComponent(lblViewTelephoneNum)
                            .addComponent(lblViewFax)
                            .addComponent(lblViewEmail)
                            .addComponent(lblViewSSN)
                            .addComponent(lblViewMedicalRecordNum)
                            .addComponent(lblViewDeviceId)
                            .addComponent(lblViewLinkedIn)
                            .addComponent(lblViewIP)
                            .addComponent(lblViewHealthPlanBnfNum)
                            .addComponent(lblViewBankAccNum)
                            .addComponent(lblViewLicenseNum)
                            .addComponent(lblViewVehicleId)
                            .addComponent(lblViewDob)
                            .addComponent(lblViewBiometricId))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(730, 730, 730)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtViewName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtViewEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewSSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewHealthPlanBnfId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewFAXNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtViewVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtViewTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtViewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtViewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtViewDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtViewIp, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtViewLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 1738, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lblViewFullFaceImage)
                                .addGap(89, 89, 89)
                                .addComponent(lblFullFaceImg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(lblCreatePersonProfile)
                        .addGap(264, 264, 264))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCreatePersonProfile, lblViewAddress, lblViewBankAccNum, lblViewBiometricId, lblViewDeviceId, lblViewDob, lblViewEmail, lblViewFax, lblViewFullFaceImage, lblViewHealthPlanBnfNum, lblViewIP, lblViewLicenseNum, lblViewLinkedIn, lblViewMedicalRecordNum, lblViewName, lblViewSSN, lblViewTelephoneNum, lblViewVehicleId});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCreatePersonProfile)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblViewName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewName)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAddress)
                    .addComponent(txtViewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblViewDob)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtViewDob, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewTelephoneNum)
                    .addComponent(txtViewTeleNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblViewFax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblViewEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblViewSSN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewMedicalRecordNum)
                        .addGap(18, 18, 18)
                        .addComponent(lblViewHealthPlanBnfNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewBankAccNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblViewLicenseNum))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtViewFAXNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtViewSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtViewMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewHealthPlanBnfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtViewBankAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewVehicleId)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtViewLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewVehicleId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblViewDeviceId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblViewLinkedIn)
                        .addGap(18, 18, 18)
                        .addComponent(lblViewIP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtViewDeviceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtViewLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtViewIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFullFaceImg, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(lblBiometric, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblViewBiometricId)
                    .addComponent(lblViewFullFaceImage))
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCreatePersonProfile, lblViewAddress, lblViewBankAccNum, lblViewBiometricId, lblViewDeviceId, lblViewDob, lblViewEmail, lblViewFax, lblViewFullFaceImage, lblViewHealthPlanBnfNum, lblViewIP, lblViewLicenseNum, lblViewLinkedIn, lblViewMedicalRecordNum, lblViewName, lblViewSSN, lblViewTelephoneNum, lblViewVehicleId, txtViewAddress, txtViewBankAccNum, txtViewDeviceId, txtViewEmailId, txtViewFAXNum, txtViewHealthPlanBnfId, txtViewIp, txtViewLicenseNum, txtViewLinkedin, txtViewMedicalRecordNum, txtViewName, txtViewSSN, txtViewTeleNum, txtViewVehicleId});

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtViewIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewIpActionPerformed

    private void txtViewBankAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewBankAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewBankAccNumActionPerformed

    private void txtViewDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewDobActionPerformed

    private void txtViewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblCreatePersonProfile;
    private javax.swing.JLabel lblFullFaceImg;
    private javax.swing.JLabel lblViewAddress;
    private javax.swing.JLabel lblViewBankAccNum;
    private javax.swing.JLabel lblViewBiometricId;
    private javax.swing.JLabel lblViewDeviceId;
    private javax.swing.JLabel lblViewDob;
    private javax.swing.JLabel lblViewEmail;
    private javax.swing.JLabel lblViewFax;
    private javax.swing.JLabel lblViewFullFaceImage;
    private javax.swing.JLabel lblViewHealthPlanBnfNum;
    private javax.swing.JLabel lblViewIP;
    private javax.swing.JLabel lblViewLicenseNum;
    private javax.swing.JLabel lblViewLinkedIn;
    private javax.swing.JLabel lblViewMedicalRecordNum;
    private javax.swing.JLabel lblViewName;
    private javax.swing.JLabel lblViewSSN;
    private javax.swing.JLabel lblViewTelephoneNum;
    private javax.swing.JLabel lblViewVehicleId;
    private javax.swing.JTextField txtViewAddress;
    private javax.swing.JTextField txtViewBankAccNum;
    private javax.swing.JTextField txtViewDeviceId;
    private javax.swing.JTextField txtViewDob;
    private javax.swing.JTextField txtViewEmailId;
    private javax.swing.JTextField txtViewFAXNum;
    private javax.swing.JTextField txtViewHealthPlanBnfId;
    private javax.swing.JTextField txtViewIp;
    private javax.swing.JTextField txtViewLicenseNum;
    private javax.swing.JTextField txtViewLinkedin;
    private javax.swing.JTextField txtViewMedicalRecordNum;
    private javax.swing.JTextField txtViewName;
    private javax.swing.JTextField txtViewSSN;
    private javax.swing.JTextField txtViewTeleNum;
    private javax.swing.JTextField txtViewVehicleId;
    // End of variables declaration//GEN-END:variables
}
