/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.util.UUID;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krupa
 */
public class ManageDeliveryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryJPanel
     */
    EcoSystem ecosystem;
    UserAccountDirectory userAccountList;
    
    public ManageDeliveryJPanel(UserAccount userAccount,EcoSystem ecosystem) {
        initComponents();
        this.ecosystem=ecosystem;
        insertIntoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnCreateRestaurant = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDelivery = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Delivery Person Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 940, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 150, 30));

        txtUserName.setBackground(new java.awt.Color(153, 0, 0));
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 290, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, 30));

        txtPassword.setBackground(new java.awt.Color(153, 0, 0));
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 290, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, 30));

        txtName.setBackground(new java.awt.Color(153, 0, 0));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 290, 30));

        btnCreateRestaurant.setIcon(new javax.swing.ImageIcon("C:\\Users\\krupa\\Downloads\\Assignment5Skeleton\\db4odemo\\add1.png")); // NOI18N
        btnCreateRestaurant.setText("Create");
        btnCreateRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRestaurantActionPerformed(evt);
            }
        });
        add(btnCreateRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 90, 30));

        btnModify.setIcon(new javax.swing.ImageIcon("C:\\Users\\krupa\\Downloads\\Assignment5Skeleton\\db4odemo\\edit1.png")); // NOI18N
        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        add(btnModify, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 90, 30));

        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\krupa\\Downloads\\Assignment5Skeleton\\db4odemo\\del.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 100, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 170, 30));

        txtPhone.setBackground(new java.awt.Color(153, 0, 0));
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 290, 30));

        tblDelivery.setBackground(new java.awt.Color(153, 0, 0));
        tblDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblDelivery.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblDelivery.setForeground(new java.awt.Color(255, 255, 255));
        tblDelivery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Phone", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDelivery.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblDelivery.setGridColor(new java.awt.Color(255, 255, 255));
        tblDelivery.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveryMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDelivery);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            txtName.setEditable(true);
        }
        else{
            txtName.setEditable(false);
            JOptionPane.showMessageDialog(txtName, "Invalid entry. Please enter letters only.");
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void btnCreateRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRestaurantActionPerformed
        // TODO add your handling code here:
        int flag = 1;
        String deliveryManId = UUID.randomUUID().toString();

        if( (txtName.getText().isEmpty() || txtName.getText() == null)){
            JOptionPane.showMessageDialog(txtName, "Error: Name is null or empty");
            flag = 0;
            return;
        }

        if(txtPhone.getText().isEmpty() || txtPhone.getText() == null || !txtPhone.getText().matches("^\\d{3}-\\d{3}-\\d{4}$")){
            JOptionPane.showMessageDialog(this,"Error: Phone Number must be in the form XXX-XXX-XXXX and cannot be null or empty");
            return;
        }

        if( (txtUserName.getText().isEmpty() || txtUserName.getText() == null)){
            JOptionPane.showMessageDialog(txtUserName, "Error: Username is null or empty");
            flag = 0;
            return;
        }

        if( (txtPassword.getText().isEmpty() || txtPassword.getText() == null)){
            JOptionPane.showMessageDialog(txtPassword, "Error: Password is null or empty");
            flag = 0;
            return;
        }

        if( txtUserName.getText().isEmpty()||txtPassword.getText().isEmpty()|| txtName.getText().isEmpty() || txtPhone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill all details");
            return;
        }

        if(flag == 1){
            if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtUserName.getText())){

              DeliveryMan deliveryMan = new DeliveryMan(txtUserName.getText(), txtPassword.getText(), txtName.getText(), txtPhone.getText());
                deliveryMan.setDeliveryManId(deliveryManId);
                ecosystem.getUserAccountDirectory().addUserAccount(deliveryMan);
                ecosystem.getDeliveryManDirectory().addDeliveryMan(deliveryMan);

                insertIntoTable();
                txtUserName.setText("");
                txtPassword.setText("");
                txtName.setText("");
                txtPhone.setText("");
                JOptionPane.showMessageDialog(this,"Delivery Person's details are created.");
            }else{
                JOptionPane.showMessageDialog(null, "Username " + txtUserName.getText() + " already exists !!!, Please try a new one");
            }
        }
    }//GEN-LAST:event_btnCreateRestaurantActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        int flag = 1;
        if( (txtName.getText().isEmpty() || txtName.getText() == null)){
            JOptionPane.showMessageDialog(txtName, "Error: Name is null or empty");
            flag = 0;
            return;
        }


        if(txtPhone.getText().isEmpty() || txtPhone.getText() == null || !txtPhone.getText().matches("^\\d{3}-\\d{3}-\\d{4}$")){
            JOptionPane.showMessageDialog(this,"Error: Phone Number must be in the form XXX-XXX-XXXX and cannot be null or empty");
            return;
        }

        if( (txtUserName.getText().isEmpty() || txtUserName.getText() == null)){
            JOptionPane.showMessageDialog(txtUserName, "Error: Username is null or empty");
            flag = 0;
            return;
        }

        if( (txtPassword.getText().isEmpty() || txtPassword.getText() == null)){
            JOptionPane.showMessageDialog(txtPassword, "Error: Password is null or empty");
            flag = 0;
            return;
        }

        if( txtUserName.getText().isEmpty()||txtPassword.getText().isEmpty()|| txtName.getText().isEmpty()  || txtPhone.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please fill all details");
            return;
        }

        int selectedRow = tblDelivery.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
        else {
            if(flag == 1){
                for(UserAccount userAccount: ecosystem.getUserAccountDirectory().getUserAccountList()){
                    if(txtUserName.getText().equals(userAccount.getUsername())){
                        if(userAccount.getDeliveryManId()!= ecosystem.getDeliveryManDirectory().getDeliveryManList().get(selectedRow).getDeliveryManId())
                        {
                            JOptionPane.showMessageDialog(null, "Username already exists!");
                            return;
                        }
                    }
                }
                DeliveryMan deliveryMan  = ecosystem.getDeliveryManDirectory().getDeliveryManList().get(selectedRow);
                deliveryMan.setUsername(txtUserName.getText());
                deliveryMan.setPassword(txtPassword.getText());
                deliveryMan.setName(txtName.getText());
                deliveryMan.setPhone(txtPhone.getText());
                insertIntoTable();
                txtUserName.setText("");
                txtPassword.setText("");
                txtName.setText("");
                txtPhone.setText("");

                JOptionPane.showMessageDialog(this,"Delivery Person's details are updated.");

            }
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblDelivery.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
        } else {
            //            Customer customer = (Customer) tblCustomer.getValueAt(selectedRow, 0);
            DeliveryMan deliveryMan = ecosystem.getDeliveryManDirectory().getDeliveryManList().get(selectedRow);
           DeliveryManDirectory deliveryManDirectory = ecosystem.getDeliveryManDirectory();
            deliveryManDirectory.removeDeliveryMan(deliveryMan);
            JOptionPane.showMessageDialog(null, "  "  + txtUserName.getText() + " deleted");
            insertIntoTable();
            txtName.setText("");
            txtPhone.setText("");
            txtUserName.setText("");
            txtPassword.setText("");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveryMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblDelivery.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
        }
        else{
            try{
                DefaultTableModel model = (DefaultTableModel)tblDelivery.getModel();
                DeliveryMan deliveryMan = ecosystem.getDeliveryManDirectory().getDeliveryManList().get(selectedRow);
                //            Customer  customer  = (Customer) tblCustomer.getValueAt(selectedRow, 0);
                if(deliveryMan!=null){
                    txtName.setText(deliveryMan.getName());
                    txtPhone.setText(deliveryMan.getPhone());
                    txtUserName.setText(deliveryMan.getUsername());
                    txtPassword.setText(deliveryMan.getPassword());
                }
            }

            catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_tblDeliveryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateRestaurant;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDelivery;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void insertIntoTable() {
        DeliveryManDirectory deliveryManDirectory = ecosystem.getDeliveryManDirectory();
        DefaultTableModel model = (DefaultTableModel) tblDelivery.getModel();
        tblDelivery.setEditingRow(-1);

        model.setRowCount(0);
        for (DeliveryMan deliveryMan : deliveryManDirectory.getDeliveryManList()) {
                    Object[] row = new Object[4];
                    row[0] = deliveryMan.getName();
                    row[1] = deliveryMan.getPhone();
                    row[2] = deliveryMan.getUsername();
                    row[3] = deliveryMan.getPassword();

                    model.addRow(row);
                
            }
    }
}
